name: austin_eda
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - python
  - ipython
  - ipykernel
  - jupyter
  - pandas==0.23.4
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - geopandas
  - pyshp
  - shapely
  - seaborn
  - folium
  - requests
  - beautifulsoup4
  - xlrd
  - lxml
  - html5lib
  - plotly
  - plotly_express
  - geopandas
  - scikit-learn
  - pylint
  - autopep8
  - pip:
    - keplergl