name: austin_eda
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - python
  - ipython
  - ipykernel
  - jupyter
  - pandas==0.23.4
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - geopandas
  - seaborn
  - requests
  - beautifulsoup4
  - lxml
  - html5lib
  - plotly
  - plotly_express
  - boto3
  - curl
  - pillow
  - scikit-learn
  - pymc3
  - pylint
  - autopep8
  - pip